from .admin import *
from .announcement import *
from .assignment import *
from .attendance import *
from .classes import *
from .event import *
from .exam import *
from .grade import *
from .lesson import *
from .parent import *
from .result import *
from .teacher import *
from .subject import *
from .student import *
from .user import *
